M48
; DRILL file {KiCad 9.0.6} date 2025-12-08T16:48:50+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-08T16:48:50+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X113.97Y-97.46
X115.24Y-49.2
X166.04Y-64.44
X166.04Y-92.38
M30
